apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: bwade-dev-tls
spec:
  secretName: bwade-dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: bwade.dev
  dnsNames:
    - bwade.dev
    - www.bwade.dev
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - bwade.dev
          - www.bwade.dev
